// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF7CFWEizDDRp2XTff2uQL-LpO75Oyt6w',
    appId: '1:64173325113:web:6440a25b7e8c627584c6e8',
    messagingSenderId: '64173325113',
    projectId: 'barberwise-7e74a',
    authDomain: 'barberwise-7e74a.firebaseapp.com',
    storageBucket: 'barberwise-7e74a.firebasestorage.app',
    measurementId: 'G-87BV67PGGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLa97hmSqo23VPy29wEalOle9h3VU09g0',
    appId: '1:64173325113:android:3fdc33e526f54d2c84c6e8',
    messagingSenderId: '64173325113',
    projectId: 'barberwise-7e74a',
    storageBucket: 'barberwise-7e74a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM-YStGYrNkJZEk3FCvYYU9sY6iIGhxew',
    appId: '1:64173325113:ios:d5054e5a5a682ee484c6e8',
    messagingSenderId: '64173325113',
    projectId: 'barberwise-7e74a',
    storageBucket: 'barberwise-7e74a.firebasestorage.app',
    iosBundleId: 'com.example.barber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM-YStGYrNkJZEk3FCvYYU9sY6iIGhxew',
    appId: '1:64173325113:ios:d5054e5a5a682ee484c6e8',
    messagingSenderId: '64173325113',
    projectId: 'barberwise-7e74a',
    storageBucket: 'barberwise-7e74a.firebasestorage.app',
    iosBundleId: 'com.example.barber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF7CFWEizDDRp2XTff2uQL-LpO75Oyt6w',
    appId: '1:64173325113:web:1634d60e9a07d96584c6e8',
    messagingSenderId: '64173325113',
    projectId: 'barberwise-7e74a',
    authDomain: 'barberwise-7e74a.firebaseapp.com',
    storageBucket: 'barberwise-7e74a.firebasestorage.app',
    measurementId: 'G-DFH9L0DP2H',
  );
}
